### ISSUE TITLE
update UI

### ISSUE THREAD

**Issue by sIRwa2** [tschroedter/idasen-desk#15]
![image](https://user-images.githubusercontent.com/31706178/220898513-d81367bc-bb52-4fad-b015-aba23337168f.png)
May i suggest an UI update? love to help.

**Comment by emiltorp** [comment]
I made a fork a while back where I went the other way, instead of all custom design I went full Windows 11 native, with native notifications as well. 

In that fork i also removed all unnecessary packages and Jetbrains stuff, so I never sent a pull request. (Too cluttered)

So even though I like this design, if there should be a design update, consider to go native. At least for the notifications.

**Comment by zeroarst** [comment]
> ![image](https://user-images.githubusercontent.com/31706178/220898513-d81367bc-bb52-4fad-b015-aba23337168f.png) May i suggest an UI update? love to help.

That looks great... would love to see the new UI..

**Comment by tschroedter** [comment]
Hi, the suggested UI good. Feel free to fork the repository and implement it. I didn't  have time during the last few month to work on the project. My plan for the near future is to fix the existing bug related to the log file size, add code to support multiple users and update the UI using MAUI. MAUI will give you the native look and feel for Windows 10 and 11.

**Comment by falkenhawk** [comment]
@tschroedter is it possible to disable all notifications altogether, e.g. via `appsettings.json` file?

**Comment by tschroedter** [comment]
This feature doesn't exist yet. I'll have a look today or tomorrow and see if I can quickly add it. It shouldn't be to hard to do.

**Comment by tschroedter** [comment]
@falkenhawk I added a new advanced setting to show/hide all notifications (see [V0.0.189.0](https://github.com/tschroedter/idasen-desk/releases/tag/V0.0.189). Let me know what you think.

**Comment by falkenhawk** [comment]
Does exactly what it is meant to :) Thank you!

**Comment by tschroedter** [comment]
Done.
